/**
 * Sector pricing logic - section 2 of docs/pricing-spec-2026-09-27.md (R50,
 * 27 Sep 2026).
 *
 * `sector-prices.json` is generated by `scripts/sector-costs.mjs price` and
 * holds final prices only. This module is the one reader of it: every tile,
 * "from" figure and checkout that needs a sector price comes through here, so
 * a label or a figure is never typed into a component.
 *
 * - A cluster's price is the sector's price for the market, per tier.
 * - 1-10 clusters: price times quantity, no discount. 11 or more is a call.
 * - The "other" sector is a call.
 * - The US leads: it is the default market, and first wherever both appear.
 * - UK prices are ex VAT; VAT is added at checkout, not here.
 *
 * alwaystracked is not in the file (it is priced in pricing.ts) and
 * alwayseverywhere has no price anywhere, so the only tiers here are the two
 * sold per cluster.
 */

import raw from "./sector-prices.json" with { type: "json" };

export type SectorTier = "mentioned" | "cited";
export type Market = "us" | "uk";

/** US first, per the spec. */
export const MARKETS: Market[] = ["us", "uk"];
export const DEFAULT_MARKET: Market = "us";

/** Clusters bought at a sector price. Past this, the price is a call. */
export const MAX_CLUSTERS = 10;

type MarketPrices = { currency: "USD" | "GBP"; mentioned: number; cited: number };
type PricedEntry = { label: string; us: MarketPrices; uk: MarketPrices };
type CallEntry = { label: string; us: "call"; uk: "call" };

export type Sector = { id: string; label: string; prices: { us: MarketPrices; uk: MarketPrices } | null };

const entries = raw as unknown as Record<string, PricedEntry | CallEntry>;

/** Every sector, in the file's order, "other" included (prices null). */
export const SECTORS: Sector[] = Object.entries(entries).map(([id, e]) => ({
  id,
  label: e.label,
  prices: typeof e.us === "string" || typeof e.uk === "string" ? null : { us: e.us, uk: e.uk },
}));

export const CURRENCY: Record<Market, { code: "USD" | "GBP"; symbol: string }> = {
  us: { code: "USD", symbol: "$" },
  uk: { code: "GBP", symbol: "£" },
};

/** A monthly price, or a call where no figure can be sold. */
export type SectorQuote = { kind: "price"; amount: number; market: Market } | { kind: "call" };

export function sectorById(id: string): Sector | undefined {
  return SECTORS.find((s) => s.id === id);
}

/** What `quantity` clusters of `tier` cost a month in `sectorId`, in `market`. */
export function quoteFor(sectorId: string, market: Market, tier: SectorTier, quantity: number): SectorQuote {
  const sector = sectorById(sectorId);
  if (!sector || !sector.prices) return { kind: "call" };
  if (!Number.isInteger(quantity) || quantity < 1 || quantity > MAX_CLUSTERS) return { kind: "call" };
  return { kind: "price", amount: sector.prices[market][tier] * quantity, market };
}

/** The lowest sellable one-cluster price for a tier in a market - the "from". */
export function fromPrice(tier: SectorTier, market: Market): number {
  const figures = SECTORS.flatMap((s) => (s.prices ? [s.prices[market][tier]] : []));
  if (figures.length === 0) throw new Error("sector-prices.json has no priced sector");
  return Math.min(...figures);
}

/** "$1,495" / "£1,195". Whole units: every figure in the file is. */
export function formatPrice(amount: number, market: Market): string {
  return CURRENCY[market].symbol + amount.toLocaleString("en-US");
}

/** The UI label, "from $1,495/mo", in the shape splitPriceLabel reads. */
export function fromLabel(tier: SectorTier, market: Market = DEFAULT_MARKET): string {
  return `from ${formatPrice(fromPrice(tier, market), market)}/mo`;
}
